CREATE TABLE IF NOT EXISTS `awz_levelhud_players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `charid` INT NOT NULL,
  `identifier` VARCHAR(80) NULL,
  `level` INT NOT NULL DEFAULT 1,
  `total_xp` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_charid` (`charid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;